name: todo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
    
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.0
  json_serializable: ^6.0.0
  equatable: ^2.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  mockito: ^5.0.17
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  intl: ^0.17.0
  image_picker: ^0.8.7+4
  path_provider: ^2.0.11
  convert: ^3.1.2
  typed_data: ^1.4.0
  super_tooltip: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf    
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf    
  assets:
        - assets/plus-circle.png
        - assets/filter.png
        - assets/settings.png
        - assets/clock.png
        - assets/Union.png
        - assets/edit-2.png
        - assets/trash-2.png
        - assets/clock-d.png
        - assets/union-sign.png
        - assets/calendar.png
        - assets/pic.png
        - assets/rafiki.png