class Todo {
  final String? id; // Optional field for the ID generated by Mongoose
  final String title; // Title of the todo item
  final String description; // Description of the todo item
  final DateTime? deadline; // Optional deadline of the todo item
  final String? image; // Optional image URL
  final DateTime? createdAt; // Optional createdAt field

  Todo({
    this.id, // Initialize id as optional
    required this.title,
    required this.description,
    this.deadline,
    this.image,
    this.createdAt, // Initialize createdAt as optional
  });

  // Factory method to create a Todo from JSON (for reading todos)
  factory Todo.fromJson(Map<String, dynamic> json) {
    return Todo(
      id: json['_id'] as String?, // Parse the ID from JSON
      title: json['title'] as String,
      description: json['description'] as String,
      deadline: json['deadline'] != null
          ? DateTime.parse(json['deadline'] as String)
          : null,
      image: json['image'] as String?,
      createdAt: json['createdAt'] != null
          ? DateTime.parse(
              json['createdAt'] as String) // Parse createdAt from JSON
          : null,
    );
  }

  // Method to convert Todo to JSON (for creating todos)
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'deadline': deadline
          ?.toIso8601String(), // Use null-aware operator for optional field
    };
  }

  @override
  String toString() {
    return "$title, $description, $deadline, $image, $createdAt";
  }
}
